[project]
name = "state-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "psycopg2>=2.9.12",
    "pyham-ax25>=1.0.3",
    "pyserial>=3.5",
    "pystuffing>=0.0.4",
    "uuid>=1.30",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
